name: deploy security rules
on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Download Artifact
              uses: actions/download-artifact@master
              with:
                  path: .
            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only firestore:rules
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
